markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
# NOTE: Agents must always consult Microsoft Learn / Docs via MCP tools (m365AgentsToolkit, Microsoft Docs search)
# for any Microsoft Agent Framework or Azure capability guidance; never assume prior cached knowledge.
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
